CollegeBuffer/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CollegeBuffer.DAL.Model;

namespace CollegeBuffer.Models
{
    public class GroupVM
    {
        public Group ParentGroup { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Group Name")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        public string ParentGroupId { get; set; }

        public Collection<User> Admins { get; set; }
    }
}

CollegeBuffer/Models/Groups.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using CollegeBuffer.DAL.Model;

namespace CollegeBuffer.Models
{
    public class Groups
    {
        public Groups()
        {
            GroupPath = new List<Group>();
            AdministrativeRole = false;
        }
        public List<Group> GroupPath { get; set; }
        public Group[] ChildGroups { get; set; }

        public bool AdministrativeRole { get; set; }
 
    }
}

CollegeBuffer/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CollegeBuffer.BLL;
using CollegeBuffer.DAL.Model;
using CollegeBuffer.Models;
using CollegeBuffer.Special;

namespace CollegeBuffer.Controllers
{
    public class AnnouncementsController : Controller
    {
        //
        // GET: /Announcements/
        public string New(GroupPage model)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return "F";

            var db = DbUnitOfWork.NewInstance();
            var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
            var group = db.GroupsRepository.Get(new Guid(model.GroupId));

            if (group == null) return "F";

            var announcement = new Announcement()
            {
                Group = group,
                Date = DateTime.Now,
                Message = model.NewAnnouncement.Message,
                Title = model.NewAnnouncement.Title,
                User = myUser
            };

            return db.AnnouncementsRepository.Insert(announcement) != null ? "K" : "F";
        }

        public ActionResult Announcement(string id, int asPartial = 0)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return Content("Invalid Announcement!");

            var db = DbUnitOfWork.NewInstance();
            var announcement = db.AnnouncementsRepository.Get(new Guid(id));

            if (asPartial == 1)
                return PartialView(announcement);
            return View(announcement);
        }
	}
}

CollegeBuffer/Controllers/GroupsController.cs
using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;
using CollegeBuffer.BLL;
using CollegeBuffer.DAL.Model;
using CollegeBuffer.DAL.Model.Enums;
using CollegeBuffer.Models;
using CollegeBuffer.Special;

namespace CollegeBuffer.Controllers
{
    public class GroupsController : Controller
    {

        public ActionResult Index(string id = null, int asPartial = 0)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return Redirect("/Home/Login");

            using (var db = DbUnitOfWork.NewInstance())
            {
                var model = new Groups();
                Group currentGroup = null;

                if (id == null || (currentGroup = db.GroupsRepository.Get(new Guid(id))) == null)
                {
                    model.ChildGroups = db.GroupsRepository.GetAllSuperGroups();
                    if (MySession.Current.UserDetails.Role == UserRoles.Administrator)
                        model.AdministrativeRole = true;
                }
                else
                {
                    model.ChildGroups = currentGroup.SubGroups.ToArray();
                    var group = currentGroup;
                    while ((group = group.SuperGroup) != null)
                    {
                        model.GroupPath.Insert(0, group);
                    }
                    model.GroupPath.Add(currentGroup);

                    var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                    if (myUser.GroupsAsAdministrator.Contains(currentGroup) || myUser.Role == UserRoles.Administrator)
                        model.AdministrativeRole = true;
                }

                if (asPartial == 1)
                    return PartialView(model);
                return View(model);
            }
        }

        public ActionResult Create(string id = null, int asPartial = 0)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return RedirectPermanent("/Home/Login");

            using (var db = DbUnitOfWork.NewInstance())
            {
                var model = new GroupVM();
                if (id != null)
                {
                    var parentGroup = db.GroupsRepository.Get(new Guid(id));
                    if (parentGroup == null)
                        return RedirectPermanent("/Groups/Index");
                    var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                    if (!myUser.GroupsAsAdministrator.Contains(parentGroup) && myUser.Role != UserRoles.Administrator)
                        return RedirectPermanent("/Groups/Index");

                    model.ParentGroup = parentGroup;
                }
                else if (MySession.Current.UserDetails.Role != UserRoles.Administrator)
                {
                    return RedirectPermanent("/Home/Login");
                }

                if (asPartial == 1)
                    return PartialView(model);
                return View(model);
            }
        }

        public string New(GroupVM model)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return "F";

            using (var db = DbUnitOfWork.NewInstance())
            {
                Group parentGroup = null;
                if (model.ParentGroupId != null)
                {
                    parentGroup = db.GroupsRepository.Get(new Guid(model.ParentGroupId));
                    var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                    if (parentGroup == null ||
                        (myUser.GroupsAsAdministrator.FirstOrDefault(p => p.Id == parentGroup.Id) ==
                         null && myUser.Role != UserRoles.Administrator))
                        return "F";
                }
                else if (MySession.Current.UserDetails.Role != UserRoles.Administrator)
                    return "F";

                var group = new Group
                {
                    Description = model.Description,
                    Name = model.Name,
                    SuperGroup = parentGroup,
                };
                var user = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                group.Administrators.Add(user);

                var insertionReult = db.GroupsRepository.Insert(group);

                return insertionReult != null ? "K" : "F";
            }
        }

        public string Delete(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || id == null)
                return "F";

            using (var db = DbUnitOfWork.NewInstance())
            {
                var group = db.GroupsRepository.Get(new Guid(id));
                var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                if (myUser.GroupsAsAdministrator.FirstOrDefault(p => p.Id == group.Id) ==
                     null && myUser.Role != UserRoles.Administrator)
                    return "F";

                return db.GroupsRepository.Delete(group) ? "K" : "F";
            }
        }

        public string Join(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || id == null)
                return "F";

            using (var db = DbUnitOfWork.NewInstance())
            {
                var group = db.GroupsRepository.Get(new Guid(id));
                var myUser = db.UsersRepository.Get(MySession.Current.UserDetails.Id);
                if (myUser.GroupsAsAdministrator.Union(myUser.GroupsAsStudent).FirstOrDefault(p => p.Id == group.Id) ==
                    null)
                {
                    myUser.GroupsAsStudent.Add(group);
                    return db.UsersRepository.Update(myUser) != null ? "K" : "F";
                }

                return "F";
            }

        }

        public ActionResult Group(string id, int asPartial = 0)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null)
                return Redirect("/Home/Login");

            var model = new GroupPage();
            var db = DbUnitOfWork.NewInstance();
            Group group = null;

            if (id != null)
                group = db.GroupsRepository.Get(new Guid(id));

            if (group != null)
            {
                model.Announcements = new Collection<Announcement>(group.Announcements.OrderByDescending(p=>p.Date).ToArray());
                model.Events = new Collection<Event>(group.Events.OrderByDescending(p=>p.DateCreated).ToArray());
                model.Description = group.Description;
                model.Name = group.Name;
                model.GroupId = group.Id.ToString();
            }

            if (asPartial == 1)
                return PartialView(model);
            return View(model);
        }

    }
}

CollegeBuffer/Views/Groups/Create.cshtml
@model CollegeBuffer.Models.GroupVM

<h1>Create a new group</h1>

@using (Ajax.BeginForm("New", "Groups", new AjaxOptions { OnBegin = "if(stop)e.preventDefault();$('#loading').show();stop=true;", OnSuccess = "create(data,'Groups', 'Index', '');stopForm=false;setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }))
{
    <input type="hidden" name="ParentGroupId" value="@(Model.ParentGroup!=null?Model.ParentGroup.Id.ToString():"")" />

    <table class="table">
        <tr>
            <td>Member of</td>
            <td>@(Model.ParentGroup != null ? Model.ParentGroup.Name : "-")</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Name)</td>
            <td>@Html.TextBoxFor(m => m.Name)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Description)</td>
            <td>@Html.TextAreaFor(m => m.Description)</td>
        </tr>
    </table>

    <input type="submit" class="btn btn-lg btn-success" value="Create group!" />
}

CollegeBuffer/Views/Groups/Group.cshtml
@model CollegeBuffer.Models.GroupPage

<h1>@Model.Name</h1>
<h3>@Model.Description</h3>

<hr />

<button class="btn btn-lg btn-primary" onclick="$('#newannouncement').toggle()">Add an announcement</button>
<div id="newannouncement" class="panel panel-default" style="display: none;">
    <div class="panel-body">
        @using (Ajax.BeginForm("New", "Announcements", new AjaxOptions { OnBegin = "if(stop)e.preventDefault();$('#loading').show();stop=true;", OnSuccess = "create(data,'Groups', 'Group', '" + Model.GroupId + "');stopForm=false;setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }))
        {
            @Html.HiddenFor(m => m.GroupId)
            <table class="table">
                <tr>
                    <td>@Html.LabelFor(m => m.NewAnnouncement.Title)</td>
                    <td>@Html.TextBoxFor(m => m.NewAnnouncement.Title)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(m => m.NewAnnouncement.Message)</td>
                    <td>@Html.TextAreaFor(m => m.NewAnnouncement.Message)</td>
                </tr>
            </table>
            <input type="submit" value="Create Announcement!" class="btn btn-lg btn-success" />
        }
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title">Announcements</h1>
    </div>
    <ul class="list-group">

        @if (Model.Announcements != null && Model.Announcements.Count > 0)
        {
            foreach (var announcement in Model.Announcements)
            {
                <li class="list-group-item">
                    <h4><a href="/Users/User/@announcement.User.Id"><b>@announcement.User.Username</b></a> posted <a href="/Announcements/Announcement/@announcement.Id"><b>@announcement.Title</b></a> at <i>@announcement.Date.ToString()</i>.</h4>
                    <hr />
                    <p>@announcement.Message</p>
                    <hr />
                    @if (announcement.Comments != null && announcement.Comments.Count > 0)
                    {
                        
                        <ul class="list-group">
                            @foreach (var comment in announcement.Comments.OrderBy(p => p.Date))
                            {
                                <li class="list-group-item list-group-item-info">
                                    <b>@comment.User.Username</b> at <i>@comment.Date.ToString()</i> said:<br />
                                    @comment.Text
                                </li>
                            }
                        </ul>
                    }
                    <div class="input-group">
                        <input id="comment" type="text" class="form-control" />
                        <span class="input-group-btn">
                            <button id="submitlink" class="btn btn-default" onclick="comment('/Comments/New/@announcement.Id', $('#comment').val())">Leave a comment!</button>
                        </span>
                    </div><!-- /input-group -->
                </li>
            }
        }
        else
        {
            <li class="list-group-item"><br /><p>Nothing to see here...</p></li>
        }

    </ul>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title">Events</h1>
    </div>
    <ul class="list-group">

        @if (Model.Events != null && Model.Events.Count > 0)
        {
            foreach (var oneEvent in Model.Events)
            {
                <li class="list-group-item">
                    <h4><a href="/Events/Event/@oneEvent.Id"><b>@oneEvent.Title</b></a> added at <i>@oneEvent.DateCreated.ToString()</i>.</h4>
                    <hr />
                    <p>@oneEvent.Message</p>
                    <hr />
                    <p>Start date: @oneEvent.StartDate | End date: @oneEvent.EndDate | Place: @oneEvent.Place</p>
                    <hr />
                    @if (oneEvent.Comments != null && oneEvent.Comments.Count > 0)
                    {
                        
                        <ul class="list-group">
                            @foreach (var comment in oneEvent.Comments.OrderBy(p => p.Date))
                            {
                                <li class="list-group-item list-group-item-info">
                                    <b>@comment.User.Username</b> at <i>@comment.Date.ToString()</i> said:<br />
                                    @comment.Text
                                </li>
                            }
                        </ul>
                    }
                    <div class="input-group">
                        <input id="comment" type="text" class="form-control" />
                        <span class="input-group-btn">
                            <button id="submitlink" class="btn btn-default" onclick="comment('/Comments/New/@oneEvent.Id', $('#comment').val())">Leave a comment!</button>
                        </span>
                    </div><!-- /input-group -->
                </li>
            }
        }
        else
        {
            <li class="list-group-item"><br /><p>Nothing to see here...</p></li>
        }

    </ul>
</div>

CollegeBuffer/Views/Groups/Index.cshtml
@using CollegeBuffer.DAL.Model
@using Microsoft.Ajax.Utilities
@model CollegeBuffer.Models.Groups


<ol class="breadcrumb" style="font-size: 18px;">
    <li><a href="/Groups/Index/" onclick='go("Groups", "Index", "");'>College Groups</a></li>
    @if (Model.GroupPath != null && Model.GroupPath.Count > 0)
    {
        var i = 0;
        foreach (var path in Model.GroupPath)
        {
            i++;
            if (i < Model.GroupPath.Count)
            {
                <li><a href="/Groups/Index/@path.Id" onclick='go("Groups", "Index", "@path.Id")'>@path.Name</a></li>
            }
            else
            {
                <li class="active">@path.Name</li>
            }
        }
    }
    @if (!Model.AdministrativeRole && Model.GroupPath != null && Model.GroupPath.Count > 0)
    {
        @Ajax.ActionLink("Join group!", "Join/" + Model.GroupPath.Last().Id, "Groups", new AjaxOptions { OnBegin = "if(stop){e.preventDefault();return false;}stop=true;", OnSuccess = "join(data);setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }, new { @class = "btn btn-sm btn-primary", @style="margin-left: 10px;" });
    }
</ol>


@if (Model.AdministrativeRole)
{
    <a href="/Groups/Create/@(Model.GroupPath != null && Model.GroupPath.Count > 0?Model.GroupPath.Last().Id.ToString():"")" onclick='go("groups", "Create" , "@(Model.GroupPath != null && Model.GroupPath.Count > 0?Model.GroupPath.Last().Id.ToString():"")" ) ' class="btn btn-lg btn-success">Create a group at the current path!</a>
}


<br />
<br />

@if (Model.ChildGroups == null)
{
    <h1>No subgroups to show!</h1>
}
else
{
    <table class="table">
        @foreach (var group in Model.ChildGroups)
        {
            <tr>
                <td><a href="/Groups/Index/@group.Id" onclick='go("Groups", "Index", "@group.Id")'>@group.Name</a></td>
                @if (Model.AdministrativeRole)
                {
                    <td>
                        <span class="btn-group">
                            <a href="/Groups/Edit/@group.Id" class="btn btn-warning" onclick='go("Groups", "Edit", "@group.Id")'>
                                Edit
                            </a>
                            @Ajax.ActionLink("Delete", "Delete/" + group.Id, "Groups", new AjaxOptions { OnBegin = "if(stop){e.preventDefault();return false;}stop=true;return ask();", OnSuccess = "document.location.reload(true);setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }, new { @class = "btn btn-danger" })
                        </span>
                    </td>
                }
            </tr>
        }
    </table>
}